services:
  server:
    image: ${ECR_REGISTRY}/qr-order-server:latest
    container_name: qr-order-server
    env_file:
      - ./apps/server/.env
    environment:
      CORS_ORIGINS: http://www.qr-order-demo.it.kr,http://admin.qr-order-demo.it.kr
    restart: unless-stopped
    networks:
      - server-network

  nginx:
    image: nginx:alpine
    container_name: qr-order-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.server.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
