services:
  server:
    image: ${ECR_REGISTRY}/qr-order-server:latest
    container_name: qr-order-server
    environment:
      CORS_ORIGINS: https://www.qr-order-demo.it.kr,https://admin.qr-order-demo.it.kr,www.qr-order-demo.it.kr,admin.qr-order-demo.it.kr
    restart: unless-stopped
    networks:
      - server-network

  nginx:
    image: nginx:alpine
    container_name: qr-order-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.server.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
